run:
  tests: false
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
  - nlreturn
  - lll
  - wsl
  - typecheck
  - wrapcheck
  - testpackage
  - golint
  - interfacer
  - scopelint
  - paralleltest
  - gci
  - maligned
  - gochecknoglobals
  - exhaustivestruct
  - gochecknoinits
  - gofumpt
  - funlen # Scraper functions are sometimes large

output:
  print-issued-lines: false

linters-settings:
  gofmt:
    simplify: false # The simplify flag messes up some scraper config
